on: [push, pull_request, workflow_dispatch]
name: CI
jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -v ./...
